# Importing libraries

In [3]:
# import 'pandas' library
import pandas as pd

# Reading file

In [5]:
# reading 'xls' file
df_vendas = pd.read_csv('vendas.xls')

# show dataframe
df_vendas

    data_venda    produto  quantidade vendedor    regiao  preco_unitario
0   2023-01-01  Produto A         100     João   Sudeste            50.0
1   2023-01-02  Produto B          75    Maria       Sul            35.0
2   2023-01-03  Produto C         120   Carlos     Norte            60.0
3   2023-01-04  Produto A          90      Ana  Nordeste            55.0
4   2023-01-05  Produto B         110     João   Sudeste            40.0
5   2023-01-06  Produto C          85    Maria       Sul            58.0
6   2023-01-07  Produto A          95   Carlos     Norte            48.0
7   2023-01-08  Produto B          70      Ana  Nordeste            37.0
8   2023-01-09  Produto C         105     João   Sudeste            62.0
9   2023-01-10  Produto A          80    Maria       Sul            45.0
10  2023-01-11  Produto B         115   Carlos     Norte            52.0
11  2023-01-12  Produto C          88      Ana  Nordeste            41.0
12  2023-01-13  Produto A          97     João   Sudeste            57.0
13  2023-01-14  Produto B          68    Maria       Sul            38.0
14  2023-01-15  Produto C         110   Carlos     Norte            55.0
15  2023-01-16  Produto A          82      Ana  Nordeste            42.0
16  2023-01-17  Produto B         105     João   Sudeste            63.0
17  2023-01-18  Produto C          78    Maria       Sul            40.0
18  2023-01-19  Produto A          92   Carlos     Norte            58.0
19  2023-01-20  Produto B          72      Ana  Nordeste            44.0
20  2023-01-21  Produto C          98     João   Sudeste            67.0
21  2023-01-22  Produto A          85    Maria       Sul            42.0
22  2023-01-23  Produto B         120   Carlos     Norte            60.0
23  2023-01-24  Produto C          76      Ana  Nordeste            46.0
24  2023-01-25  Produto A          88     João   Sudeste            68.0
25  2023-01-26  Produto B          65    Maria       Sul            39.0
26  2023-01-27  Produto C         112   Carlos     Norte            57.0
27  2023-01-28  Produto A          78      Ana  Nordeste            43.0
28  2023-01-29  Produto B         110     João   Sudeste            65.0
29  2023-01-30  Produto C          82    Maria       Sul            41.0
30  2023-01-31  Produto A          95   Carlos     Norte            59.0
31  2023-02-01  Produto B          70      Ana  Nordeste            45.0
32  2023-02-02  Produto C         105     João   Sudeste            70.0
33  2023-02-03  Produto A          80    Maria       Sul            44.0
34  2023-02-04  Produto B         118   Carlos     Norte            62.0
35  2023-02-05  Produto C          72      Ana  Nordeste            47.0
36  2023-02-06  Produto A          92     João   Sudeste            73.0
37  2023-02-07  Produto B          68    Maria       Sul            45.0
38  2023-02-08  Produto C         102   Carlos     Norte            63.0
39  2023-02-09  Produto A          86      Ana  Nordeste            49.0
40  2023-02-10  Produto B         112     João   Sudeste            75.0
41  2023-02-11  Produto C          80    Maria       Sul            47.0
42  2023-02-12  Produto A          98   Carlos     Norte            65.0
43  2023-02-13  Produto B          72      Ana  Nordeste            50.0
44  2023-02-14  Produto C         108     João   Sudeste            78.0
45  2023-02-15  Produto A          84    Maria       Sul            49.0
46  2023-02-16  Produto B         126   Carlos     Norte            68.0
47  2023-02-17  Produto C          74      Ana  Nordeste            52.0
48  2023-02-18  Produto A          90     João   Sudeste            80.0
49  2023-02-19  Produto B          65    Maria       Sul            50.0
50  2023-02-20  Produto C         100   Carlos     Norte            70.0

# Verifications and validations

In [6]:
# verify the data type
df_vendas.dtypes

data_venda         object
produto            object
quantidade          int64
vendedor           object
regiao             object
preco_unitario    float64
dtype: object

In [37]:
# check for missing values
if df_vendas.isna().any().any():
  df_vendas = df_vendas.fillna(0)

# Columns manipulations

In [39]:
# rename the 'data' column
df_vendas = df_vendas.rename(columns={'data_venda': 'data'})
df_vendas

          data    produto  quantidade vendedor    regiao  preco_unitario
0   2023-01-01  Produto A         100     João   Sudeste            50.0
1   2023-01-02  Produto B          75    Maria       Sul            35.0
2   2023-01-03  Produto C         120   Carlos     Norte            60.0
3   2023-01-04  Produto A          90      Ana  Nordeste            55.0
4   2023-01-05  Produto B         110     João   Sudeste            40.0
5   2023-01-06  Produto C          85    Maria       Sul            58.0
6   2023-01-07  Produto A          95   Carlos     Norte            48.0
7   2023-01-08  Produto B          70      Ana  Nordeste            37.0
8   2023-01-09  Produto C         105     João   Sudeste            62.0
9   2023-01-10  Produto A          80    Maria       Sul            45.0
10  2023-01-11  Produto B         115   Carlos     Norte            52.0
11  2023-01-12  Produto C          88      Ana  Nordeste            41.0
12  2023-01-13  Produto A          97     João   Sudeste            57.0
13  2023-01-14  Produto B          68    Maria       Sul            38.0
14  2023-01-15  Produto C         110   Carlos     Norte            55.0
15  2023-01-16  Produto A          82      Ana  Nordeste            42.0
16  2023-01-17  Produto B         105     João   Sudeste            63.0
17  2023-01-18  Produto C          78    Maria       Sul            40.0
18  2023-01-19  Produto A          92   Carlos     Norte            58.0
19  2023-01-20  Produto B          72      Ana  Nordeste            44.0
20  2023-01-21  Produto C          98     João   Sudeste            67.0
21  2023-01-22  Produto A          85    Maria       Sul            42.0
22  2023-01-23  Produto B         120   Carlos     Norte            60.0
23  2023-01-24  Produto C          76      Ana  Nordeste            46.0
24  2023-01-25  Produto A          88     João   Sudeste            68.0
25  2023-01-26  Produto B          65    Maria       Sul            39.0
26  2023-01-27  Produto C         112   Carlos     Norte            57.0
27  2023-01-28  Produto A          78      Ana  Nordeste            43.0
28  2023-01-29  Produto B         110     João   Sudeste            65.0
29  2023-01-30  Produto C          82    Maria       Sul            41.0
30  2023-01-31  Produto A          95   Carlos     Norte            59.0
31  2023-02-01  Produto B          70      Ana  Nordeste            45.0
32  2023-02-02  Produto C         105     João   Sudeste            70.0
33  2023-02-03  Produto A          80    Maria       Sul            44.0
34  2023-02-04  Produto B         118   Carlos     Norte            62.0
35  2023-02-05  Produto C          72      Ana  Nordeste            47.0
36  2023-02-06  Produto A          92     João   Sudeste            73.0
37  2023-02-07  Produto B          68    Maria       Sul            45.0
38  2023-02-08  Produto C         102   Carlos     Norte            63.0
39  2023-02-09  Produto A          86      Ana  Nordeste            49.0
40  2023-02-10  Produto B         112     João   Sudeste            75.0
41  2023-02-11  Produto C          80    Maria       Sul            47.0
42  2023-02-12  Produto A          98   Carlos     Norte            65.0
43  2023-02-13  Produto B          72      Ana  Nordeste            50.0
44  2023-02-14  Produto C         108     João   Sudeste            78.0
45  2023-02-15  Produto A          84    Maria       Sul            49.0
46  2023-02-16  Produto B         126   Carlos     Norte            68.0
47  2023-02-17  Produto C          74      Ana  Nordeste            52.0
48  2023-02-18  Produto A          90     João   Sudeste            80.0
49  2023-02-19  Produto B          65    Maria       Sul            50.0
50  2023-02-20  Produto C         100   Carlos     Norte            70.0

In [40]:
# create a new column
df_vendas['receita_total'] = df_vendas['quantidade'] * df_vendas['preco_unitario']
df_vendas

,data,produto,quantidade,vendedor,regiao,preco_unitario,receita_total
0,2023-01-01,Produto A,100,João,Sudeste,50.0,5000.0
1,2023-01-02,Produto B,75,Maria,Sul,35.0,2625.0
2,2023-01-03,Produto C,120,Carlos,Norte,60.0,7200.0
3,2023-01-04,Produto A,90,Ana,Nordeste,55.0,4950.0
4,2023-01-05,Produto B,110,João,Sudeste,40.0,4400.0
5,2023-01-06,Produto C,85,Maria,Sul,58.0,4930.0
6,2023-01-07,Produto A,95,Carlos,Norte,48.0,4560.0
7,2023-01-08,Produto B,70,Ana,Nordeste,37.0,2590.0
8,2023-01-09,Produto C,105,João,Sudeste,62.0,6510.0
9,2023-01-10,Produto A,80,Maria,Sul,45.0,3600.0
10,2023-01-11,Produto B,115,Carlos,Norte,52.0,5980.0
11,2023-01-12,Produto C,88,Ana,Nordeste,41.0,3608.0
12,2023-01-13,Produto A,97,João,Sudeste,57.0,5529.0
13,2023-01-14,Produto B,68,Maria,Sul,38.0,2584.0
14,2023-01-15,Produto C,110,Carlos,Norte,55.0,6050.0
15,2023-01-16,Produto A,82,Ana,Nordeste,42.0,3444.0
16,2023-01-17,Produto B,105,João,Sudeste,63.0,6615.0
17,2023-01-18,Produto C,78,Maria,Sul,40.0,3120.0
18,2023-01-19,Produto A,92,Carlos,Norte,58.0,5336.0
19,2023-01-20,Produto B,72,Ana,Nordeste,44.0,3168.0
20,2023-01-21,Produto C,98,João,Sudeste,67.0,6566.0
21,2023-01-22,Produto A,85,Maria,Sul,42.0,3570.0
22,2023-01-23,Produto B,120,Carlos,Norte,60.0,7200.0
23,2023-01-24,Produto C,76,Ana,Nordeste,46.0,3496.0
24,2023-01-25,Produto A,88,João,Sudeste,68.0,5984.0
25,2023-01-26,Produto B,65,Maria,Sul,39.0,2535.0
26,2023-01-27,Produto C,112,Carlos,Norte,57.0,6384.0
27,2023-01-28,Produto A,78,Ana,Nordeste,43.0,3354.0
28,2023-01-29,Produto B,110,João,Sudeste,65.0,7150.0
29,2023-01-30,Produto C,82,Maria,Sul,41.0,3362.0
30,2023-01-31,Produto A,95,Carlos,Norte,59.0,5605.0
31,2023-02-01,Produto B,70,Ana,Nordeste,45.0,3150.0
32,2023-02-02,Produto C,105,João,Sudeste,70.0,7350.0
33,2023-02-03,Produto A,80,Maria,Sul,44.0,3520.0
34,2023-02-04,Produto B,118,Carlos,Norte,62.0,7316.0
35,2023-02-05,Produto C,72,Ana,Nordeste,47.0,3384.0
36,2023-02-06,Produto A,92,João,Sudeste,73.0,6716.0
37,2023-02-07,Produto B,68,Maria,Sul,45.0,3060.0
38,2023-02-08,Produto C,102,Carlos,Norte,63.0,6426.0
39,2023-02-09,Produto A,86,Ana,Nordeste,49.0,4214.0
40,2023-02-10,Produto B,112,João,Sudeste,75.0,8400.0
41,2023-02-11,Produto C,80,Maria,Sul,47.0,3760.0
42,2023-02-12,Produto A,98,Carlos,Norte,65.0,6370.0
43,2023-02-13,Produto B,72,Ana,Nordeste,50.0,3600.0
44,2023-02-14,Produto C,108,João,Sudeste,78.0,8424.0
45,2023-02-15,Produto A,84,Maria,Sul,49.0,4116.0
46,2023-02-16,Produto B,126,Carlos,Norte,68.0,8568.0
47,2023-02-17,Produto C,74,Ana,Nordeste,52.0,3848.0
48,2023-02-18,Produto A,90,João,Sudeste,80.0,7200.0
49,2023-02-19,Produto B,65,Maria,Sul,50.0,3250.0
50,2023-02-20,Produto C,100,Carlos,Norte,70.0,7000.0

# Data filtering

In [44]:
# Data filtering by 'regiao'
df_sudeste = df_vendas[df_vendas['regiao'] == 'Sudeste']
df_nordeste = df_vendas[df_vendas['regiao'] == 'Nordeste']
df_norte = df_vendas[df_vendas['regiao'] == 'Norte']
df_sul = df_vendas[df_vendas['regiao'] == 'Sul']

In [52]:
# Show filtering data
df_norte

,data,produto,quantidade,vendedor,regiao,preco_unitario,receita_total
2,2023-01-03,Produto C,120,Carlos,Norte,60.0,7200.0
6,2023-01-07,Produto A,95,Carlos,Norte,48.0,4560.0
10,2023-01-11,Produto B,115,Carlos,Norte,52.0,5980.0
14,2023-01-15,Produto C,110,Carlos,Norte,55.0,6050.0
18,2023-01-19,Produto A,92,Carlos,Norte,58.0,5336.0
22,2023-01-23,Produto B,120,Carlos,Norte,60.0,7200.0
26,2023-01-27,Produto C,112,Carlos,Norte,57.0,6384.0
30,2023-01-31,Produto A,95,Carlos,Norte,59.0,5605.0
34,2023-02-04,Produto B,118,Carlos,Norte,62.0,7316.0
38,2023-02-08,Produto C,102,Carlos,Norte,63.0,6426.0
42,2023-02-12,Produto A,98,Carlos,Norte,65.0,6370.0
46,2023-02-16,Produto B,126,Carlos,Norte,68.0,8568.0
50,2023-02-20,Produto C,100,Carlos,Norte,70.0,7000.0